const std = @import("std");

// Core glib sources (glib_sources from glib/meson.build), minus gregex.c
// (needs external pcre2) and gio/gobject/gmodule/gthread (separate,
// unbuilt subprojects). gthread-posix.c/gthread-win32.c aren't listed:
// gthread.c #includes them directly based on G_OS_WIN32.
//
// This build.zig only targets Linux (glibc) hosts/targets: glibc ships
// working iconv() and gettext()/dgettext()/bindtextdomain() as part of
// libc itself, which gconvert.c and ggettext.c call unconditionally with
// no fallback. Windows (mingw) has neither built in -- real glib gets
// them from MSYS2/vcpkg-provided libiconv + a gettext-runtime or the
// proxy-libintl shim, which this build.zig does not attempt to vendor.
const glib_core_sources = [_][]const u8{
    "garcbox.c",
    "garray.c",
    "gasyncqueue.c",
    "gatomic.c",
    "gbacktrace.c",
    "gbase64.c",
    "gbitlock.c",
    "gbookmarkfile.c",
    "gbytes.c",
    "gcharset.c",
    "gchecksum.c",
    "gconvert.c",
    "gdataset.c",
    "gdate.c",
    "gdatetime.c",
    "gdatetime-private.c",
    "gdir.c",
    "genviron.c",
    "gerror.c",
    "gfileutils.c",
    "ggettext.c",
    "ghash.c",
    "ghmac.c",
    "ghook.c",
    "ghostutils.c",
    "giochannel.c",
    "gkeyfile.c",
    "glib-init.c",
    "glib-private.c",
    "glist.c",
    "gmain.c",
    "gmappedfile.c",
    "gmarkup.c",
    "gmem.c",
    "gmessages.c",
    "gnode.c",
    "goption.c",
    "gpathbuf.c",
    "gpattern.c",
    "gpoll.c",
    "gprimes.c",
    "gqsort.c",
    "gquark.c",
    "gqueue.c",
    "grand.c",
    "grcbox.c",
    "grefcount.c",
    "grefstring.c",
    "gscanner.c",
    "gsequence.c",
    "gshell.c",
    "gslice.c",
    "gslist.c",
    "gspawn.c",
    "gstdio.c",
    "gstrfuncs.c",
    "gstring.c",
    "gstringchunk.c",
    "gstrvbuilder.c",
    "gtestutils.c",
    "gthread.c",
    "gthreadpool.c",
    "gtimer.c",
    "gtimezone.c",
    "gtrace.c",
    "gtranslit.c",
    "gtrashstack.c",
    "gtree.c",
    "guniprop.c",
    "gutf8.c",
    "gunibreak.c",
    "gunicollate.c",
    "gunidecomp.c",
    "guri.c",
    "gutils.c",
    "guuid.c",
    "gvariant.c",
    "gvariant-core.c",
    "gvariant-parser.c",
    "gvariant-serialiser.c",
    "gvarianttypeinfo.c",
    "gvarianttype.c",
    "gversion.c",
    "gwakeup.c",
    "gprint.c",
    "gprintf.c",
    // Always built regardless of platform (see library('glib-2.0', ...)).
    "deprecated/gallocator.c",
    "deprecated/gcache.c",
    "deprecated/gcompletion.c",
    "deprecated/grel.c",
    "deprecated/gthread-deprecated.c",
    // Unix (host_system != 'windows').
    "glib-unix.c",
    "giounix.c",
    "gspawn-posix.c",
    // Linux-only (systemd journal support, no external deps).
    "gjournal-private.c",
    // subdir('libcharset').
    "libcharset/localcharset.c",
};

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    if (target.result.os.tag != .linux) {
        std.debug.print(
            "warning: this build.zig has only been verified against Linux glibc targets; " ++
                "Windows/macOS need extra work (iconv/gettext shims), see comments in build.zig\n",
            .{},
        );
    }

    const write_files = b.addWriteFiles();

    // Hand-written stand-in for glib/glibconfig.h (normally generated by
    // meson from glibconfig.h.in via extensive compiler probing). Values
    // below are hardcoded for a 64-bit little-endian Linux (LP64) target.
    _ = write_files.add("glibconfig.h",
        \\#ifndef __GLIBCONFIG_H__
        \\#define __GLIBCONFIG_H__
        \\
        \\#include <glib/gmacros.h>
        \\#include <limits.h>
        \\#include <float.h>
        \\
        \\#define GLIB_USING_SYSTEM_PRINTF 1
        \\
        \\G_BEGIN_DECLS
        \\
        \\#define G_MINFLOAT    FLT_MIN
        \\#define G_MAXFLOAT    FLT_MAX
        \\#define G_MINDOUBLE    DBL_MIN
        \\#define G_MAXDOUBLE    DBL_MAX
        \\#define G_MINSHORT    SHRT_MIN
        \\#define G_MAXSHORT    SHRT_MAX
        \\#define G_MAXUSHORT    USHRT_MAX
        \\#define G_MININT    INT_MIN
        \\#define G_MAXINT    INT_MAX
        \\#define G_MAXUINT    UINT_MAX
        \\#define G_MINLONG    LONG_MIN
        \\#define G_MAXLONG    LONG_MAX
        \\#define G_MAXULONG    ULONG_MAX
        \\
        \\typedef signed char gint8;
        \\typedef unsigned char guint8;
        \\
        \\typedef signed short gint16;
        \\typedef unsigned short guint16;
        \\
        \\#define G_GINT16_MODIFIER "h"
        \\#define G_GINT16_FORMAT "hi"
        \\#define G_GUINT16_FORMAT "hu"
        \\
        \\typedef signed int gint32;
        \\typedef unsigned int guint32;
        \\
        \\#define G_GINT32_MODIFIER ""
        \\#define G_GINT32_FORMAT "i"
        \\#define G_GUINT32_FORMAT "u"
        \\
        \\#define G_HAVE_GINT64 1
        \\
        \\typedef signed long gint64;
        \\typedef unsigned long guint64;
        \\
        \\#define G_GINT64_CONSTANT(val)    (val##L)
        \\#define G_GUINT64_CONSTANT(val)    (val##UL)
        \\
        \\#define G_GINT64_MODIFIER "l"
        \\#define G_GINT64_FORMAT "li"
        \\#define G_GUINT64_FORMAT "lu"
        \\
        \\#define GLIB_SIZEOF_VOID_P 8
        \\#define GLIB_SIZEOF_LONG   8
        \\#define GLIB_SIZEOF_SIZE_T 8
        \\#define GLIB_SIZEOF_SSIZE_T 8
        \\
        \\typedef signed long gssize;
        \\typedef unsigned long gsize;
        \\#define G_GSIZE_MODIFIER "l"
        \\#define G_GSSIZE_MODIFIER "l"
        \\#define G_GSIZE_FORMAT "lu"
        \\#define G_GSSIZE_FORMAT "li"
        \\
        \\#define G_MAXSIZE    G_MAXULONG
        \\#define G_MINSSIZE    G_MINLONG
        \\#define G_MAXSSIZE    G_MAXLONG
        \\
        \\typedef gint64 goffset;
        \\#define G_MINOFFSET    G_MININT64
        \\#define G_MAXOFFSET    G_MAXINT64
        \\
        \\#define G_GOFFSET_MODIFIER      G_GINT64_MODIFIER
        \\#define G_GOFFSET_FORMAT        G_GINT64_FORMAT
        \\#define G_GOFFSET_CONSTANT(val) G_GINT64_CONSTANT(val)
        \\
        \\#define G_POLLFD_FORMAT "%d"
        \\
        \\#define GPOINTER_TO_INT(p)    ((gint)  (glong) (p))
        \\#define GPOINTER_TO_UINT(p)    ((guint) (gulong) (p))
        \\
        \\#define GINT_TO_POINTER(i)    ((gpointer) (glong) (i))
        \\#define GUINT_TO_POINTER(u)    ((gpointer) (gulong) (u))
        \\
        \\typedef signed long gintptr;
        \\typedef unsigned long guintptr;
        \\
        \\#define G_GINTPTR_MODIFIER      "l"
        \\#define G_GINTPTR_FORMAT        "li"
        \\#define G_GUINTPTR_FORMAT       "lu"
        \\
        \\#define GLIB_MAJOR_VERSION 2
        \\#define GLIB_MINOR_VERSION 89
        \\#define GLIB_MICRO_VERSION 1
        \\
        \\#define G_OS_UNIX
        \\
        \\#define G_VA_COPY va_copy
        \\
        \\#define G_HAVE_ISO_VARARGS 1
        \\
        \\#if __GNUC__ == 2 && __GNUC_MINOR__ == 95
        \\#  undef G_HAVE_ISO_VARARGS
        \\#endif
        \\
        \\#ifndef _MSC_VER
        \\# define G_HAVE_GNUC_VARARGS 1
        \\#endif
        \\
        \\#if defined(__SUNPRO_C) && (__SUNPRO_C >= 0x590)
        \\#define G_GNUC_INTERNAL __attribute__((visibility("hidden")))
        \\#elif defined(__SUNPRO_C) && (__SUNPRO_C >= 0x550)
        \\#define G_GNUC_INTERNAL __hidden
        \\#elif defined (__GNUC__) && defined (G_HAVE_GNUC_VISIBILITY)
        \\#define G_GNUC_INTERNAL __attribute__((visibility("hidden")))
        \\#else
        \\#define G_GNUC_INTERNAL
        \\#endif
        \\
        \\#define G_THREADS_ENABLED
        \\#define G_THREADS_IMPL_POSIX
        \\
        \\#define G_ATOMIC_LOCK_FREE 1
        \\
        \\#define GINT16_TO_LE(val)    ((gint16) (val))
        \\#define GUINT16_TO_LE(val)    ((guint16) (val))
        \\#define GINT16_TO_BE(val)    ((gint16) GUINT16_SWAP_LE_BE (val))
        \\#define GUINT16_TO_BE(val)    (GUINT16_SWAP_LE_BE (val))
        \\
        \\#define GINT32_TO_LE(val)    ((gint32) (val))
        \\#define GUINT32_TO_LE(val)    ((guint32) (val))
        \\#define GINT32_TO_BE(val)    ((gint32) GUINT32_SWAP_LE_BE (val))
        \\#define GUINT32_TO_BE(val)    (GUINT32_SWAP_LE_BE (val))
        \\
        \\#define GINT64_TO_LE(val)    ((gint64) (val))
        \\#define GUINT64_TO_LE(val)    ((guint64) (val))
        \\#define GINT64_TO_BE(val)    ((gint64) GUINT64_SWAP_LE_BE (val))
        \\#define GUINT64_TO_BE(val)    (GUINT64_SWAP_LE_BE (val))
        \\
        \\#define GLONG_TO_LE(val)    ((glong) GINT64_TO_LE (val))
        \\#define GULONG_TO_LE(val)    ((gulong) GUINT64_TO_LE (val))
        \\#define GLONG_TO_BE(val)    ((glong) GINT64_TO_BE (val))
        \\#define GULONG_TO_BE(val)    ((gulong) GUINT64_TO_BE (val))
        \\#define GINT_TO_LE(val)        ((gint) GINT32_TO_LE (val))
        \\#define GUINT_TO_LE(val)    ((guint) GUINT32_TO_LE (val))
        \\#define GINT_TO_BE(val)        ((gint) GINT32_TO_BE (val))
        \\#define GUINT_TO_BE(val)    ((guint) GUINT32_TO_BE (val))
        \\#define GSIZE_TO_LE(val)    ((gsize) GUINT64_TO_LE (val))
        \\#define GSSIZE_TO_LE(val)    ((gssize) GINT64_TO_LE (val))
        \\#define GSIZE_TO_BE(val)    ((gsize) GUINT64_TO_BE (val))
        \\#define GSSIZE_TO_BE(val)    ((gssize) GINT64_TO_BE (val))
        \\#define G_BYTE_ORDER G_LITTLE_ENDIAN
        \\
        \\#define GLIB_SYSDEF_POLLIN =1
        \\#define GLIB_SYSDEF_POLLOUT =4
        \\#define GLIB_SYSDEF_POLLPRI =2
        \\#define GLIB_SYSDEF_POLLHUP =16
        \\#define GLIB_SYSDEF_POLLERR =8
        \\#define GLIB_SYSDEF_POLLNVAL =32
        \\
        \\#define G_MODULE_SUFFIX "so"
        \\
        \\typedef int GPid;
        \\#define G_PID_FORMAT "i"
        \\
        \\#define GLIB_SYSDEF_AF_UNIX 1
        \\#define GLIB_SYSDEF_AF_INET 2
        \\#define GLIB_SYSDEF_AF_INET6 10
        \\
        \\#define GLIB_SYSDEF_MSG_OOB 1
        \\#define GLIB_SYSDEF_MSG_PEEK 2
        \\#define GLIB_SYSDEF_MSG_DONTROUTE 4
        \\
        \\#define G_DIR_SEPARATOR '/'
        \\#define G_DIR_SEPARATOR_S "/"
        \\#define G_SEARCHPATH_SEPARATOR ':'
        \\#define G_SEARCHPATH_SEPARATOR_S ":"
        \\
        \\G_END_DECLS
        \\
        \\#endif /* __GLIBCONFIG_H__ */
        \\
    );

    // Hand-written stand-in for glib's config.h (normally generated by
    // meson from ~150 compiler probes across the whole glib/gobject/gio
    // tree). Only a conservative subset relevant to the core glib_sources
    // above is set; every HAVE_* symbol not listed here is guarded by an
    // #ifdef with a working (if sometimes slower or less featureful)
    // fallback in the source, so leaving them undefined is safe.
    _ = write_files.add("config.h",
        \\#ifndef __CONFIG_H__
        \\#define __CONFIG_H__
        \\
        \\#define PACKAGE_NAME "glib"
        \\#define PACKAGE_VERSION "2.89.1"
        \\#define GETTEXT_PACKAGE "glib20"
        \\#define GLIB_LOCALE_DIR "/usr/share/locale"
        \\
        \\#define GLIB_INTERFACE_AGE 0
        \\#define GLIB_BINARY_AGE 8901
        \\
        \\// glibc ships a real, working gettext as part of libc itself
        \\// (unlike mingw), so enable it here rather than faking out
        \\// libintl.h with no-op macros (which would also conflict with
        \\// libintl.h's own real declarations when both are included).
        \\#define ENABLE_NLS 1
        \\#define HAVE_BIND_TEXTDOMAIN_CODESET 1
        \\
        \\// Modern glibc's vsnprintf/snprintf/printf are already C99/POSIX
        \\// compliant, so use them directly instead of bundling gnulib's
        \\// vasnprintf-based reimplementation (glib/gnulib/, not compiled
        \\// by this build.zig at all).
        \\#define USE_SYSTEM_PRINTF 1
        \\
        \\#define SIZEOF_CHAR 1
        \\#define SIZEOF_SHORT 2
        \\#define SIZEOF_INT 4
        \\#define SIZEOF_LONG 8
        \\#define SIZEOF_LONG_LONG 8
        \\#define SIZEOF_VOID_P 8
        \\#define SIZEOF_SIZE_T 8
        \\#define SIZEOF_SSIZE_T 8
        \\#define SIZEOF_PTRDIFF_T 8
        \\#define SIZEOF_WCHAR_T 4
        \\#define SIZEOF_TIME_T 8
        \\
        \\#define THREADS_POSIX 1
        \\
        \\#define HAVE_STDINT_H 1
        \\#define HAVE_INTTYPES_H 1
        \\#define HAVE_UNISTD_H 1
        \\#define HAVE_SYS_TYPES_H 1
        \\#define HAVE_SYS_TIME_H 1
        \\#define HAVE_SYS_SELECT_H 1
        \\#define HAVE_SYS_RESOURCE_H 1
        \\#define HAVE_SYS_PRCTL_H 1
        \\#define HAVE_SYS_PARAM_H 1
        \\#define HAVE_SYS_AUXV_H 1
        \\#define HAVE_DIRENT_H 1
        \\#define HAVE_POLL_H 1
        \\#define HAVE_SCHED_H 1
        \\#define HAVE_FTW_H 1
        \\#define HAVE_STDATOMIC_H 1
        \\
        \\#define HAVE_ICONV 1
        \\#define HAVE_LANGINFO_CODESET 1
        \\#define HAVE_CODESET 1
        \\#define HAVE_SETLOCALE 1
        \\
        \\#define HAVE_POLL 1
        \\#define HAVE_PPOLL 1
        \\#define HAVE_MMAP 1
        \\#define HAVE_GETAUXVAL 1
        \\#define HAVE_GETRESUID 1
        \\#define HAVE_GETPWUID_R 1
        \\#define HAVE_GETPWNAM_R 1
        \\
        \\#define HAVE_LOCALTIME_R 1
        \\#define HAVE_GMTIME_R 1
        \\#define HAVE_TIMEGM 1
        \\
        \\#define HAVE_VASPRINTF 1
        \\#define HAVE_STPCPY 1
        \\#define HAVE_STRCASECMP 1
        \\#define HAVE_STRNCASECMP 1
        \\#define HAVE_STRSIGNAL 1
        \\#define HAVE_STRERROR_R 1
        \\#define STRERROR_R_CHAR_P 1
        \\#define HAVE_MEMMEM 1
        \\
        \\#define HAVE_POSIX_MEMALIGN 1
        \\#define HAVE_FSYNC 1
        \\#define HAVE_EVENTFD 1
        \\#define HAVE_O_CLOEXEC 1
        \\#define HAVE_SOCK_CLOEXEC 1
        \\#define HAVE_POSIX_SPAWN 1
        \\#define HAVE_SPAWN_H 1
        \\
        \\#define HAVE_PTHREAD_ATTR_SETSTACKSIZE 1
        \\#define HAVE_PTHREAD_CONDATTR_SETCLOCK 1
        \\#define HAVE_PTHREAD_SETNAME_NP_WITH_TID 1
        \\#define HAVE_PTHREAD_GETNAME_NP 1
        \\#define HAVE_CLOCK_NANOSLEEP 1
        \\#define HAVE_PTHREAD_GETAFFINITY_NP 1
        \\
        \\#define HAVE_STRUCT_TM_TM_GMTOFF 1
        \\
        \\#define G_HAVE_GNUC_VISIBILITY 1
        \\
        \\#endif /* __CONFIG_H__ */
        \\
    );

    const generated_headers = write_files.getDirectory();

    // Generated via glib's own tools/gen-visibility-macros.py (same
    // generator meson uses), so these two headers are exact, not
    // hand-approximated like config.h/glibconfig.h above. Requires
    // `python` on PATH at build time.
    const gen_script = b.path("tools/gen-visibility-macros.py");

    const gen_versions = b.addSystemCommand(&.{ "python", "-B" });
    gen_versions.addFileArg(gen_script);
    gen_versions.addArgs(&.{ "2.89.1", "versions-macros" });
    gen_versions.addFileArg(b.path("glib/gversionmacros.h.in"));
    const gversionmacros_h = gen_versions.addOutputFileArg("gversionmacros.h");

    const gen_visibility = b.addSystemCommand(&.{ "python", "-B" });
    gen_visibility.addFileArg(gen_script);
    gen_visibility.addArgs(&.{ "2.89.1", "visibility-macros", "GLIB" });
    const glib_visibility_h = gen_visibility.addOutputFileArg("glib-visibility.h");

    const mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    mod.addIncludePath(generated_headers);
    mod.addIncludePath(b.path("glib"));
    // Consumers include e.g. <glib/gtypes.h>, so the parent of glib/ needs
    // to be on the include path too (matches meson's glibinc).
    mod.addIncludePath(b.path("."));
    mod.addCMacro("HAVE_CONFIG_H", "1");
    mod.addCMacro("GLIB_COMPILATION", "1");
    mod.addCMacro("G_LOG_DOMAIN", "\"GLib\"");
    mod.addCMacro("GLIB_CHARSETALIAS_DIR", "\"\"");
    // Needed for glibc GNU extensions used unconditionally by the sources
    // below: ppoll() (gmain.c), the char*-returning strerror_r()
    // (gbacktrace.c/gstrfuncs.c), etc.
    mod.addCMacro("_GNU_SOURCE", "1");

    // gversionmacros.h/glib-visibility.h are #included (as
    // "gversionmacros.h") from glib/gmacros.h et al, so they need to live
    // next to the other glib/*.h headers on the include path; addCopyFile
    // them into the same generated-headers directory used above.
    // Placed under a "glib/" subdirectory since e.g. gtypes.h includes
    // them as <glib/gversionmacros.h> / <glib/glib-visibility.h>.
    const glib_headers_dir = b.addNamedWriteFiles("glib-generated-headers");
    _ = glib_headers_dir.addCopyFile(gversionmacros_h, "glib/gversionmacros.h");
    _ = glib_headers_dir.addCopyFile(glib_visibility_h, "glib/glib-visibility.h");
    mod.addIncludePath(glib_headers_dir.getDirectory());

    mod.addCSourceFiles(.{
        .root = b.path("glib"),
        .files = &glib_core_sources,
        .flags = &.{"-std=gnu99"},
    });

    const lib = b.addLibrary(.{
        .name = "glib-2.0",
        .linkage = .static,
        .root_module = mod,
    });
    b.installArtifact(lib);

    // Install headers so zig-out/include is directly usable by a
    // consumer: <glib.h> plus every glib/*.h (galloca.h, garray.h, ...)
    // under zig-out/include/glib/, and the hand-written/generated headers
    // that normally live in meson's separate config/glibinc dirs.
    lib.installHeader(b.path("glib/glib.h"), "glib.h");
    b.installDirectory(.{
        .source_dir = b.path("glib"),
        .install_dir = .header,
        .install_subdir = "glib",
        .include_extensions = &.{".h"},
    });
    lib.installHeader(generated_headers.join(b.allocator, "glibconfig.h") catch @panic("OOM"), "glibconfig.h");
    lib.installHeader(gversionmacros_h, "glib/gversionmacros.h");
    lib.installHeader(glib_visibility_h, "glib/glib-visibility.h");
}
