const std = @import("std");

// Core glib sources (glib_sources from glib/meson.build), minus gregex.c
// (needs external pcre2) and gio/gobject/gmodule/gthread (separate,
// unbuilt subprojects). gthread-posix.c/gthread-win32.c aren't listed:
// gthread.c #includes them directly based on G_OS_WIN32.
//
// This build.zig only targets Linux (glibc) hosts/targets: glibc ships
// working iconv() and gettext()/dgettext()/bindtextdomain() as part of
// libc itself, which gconvert.c and ggettext.c call unconditionally with
// no fallback. Windows (mingw) has neither built in -- real glib gets
// them from MSYS2/vcpkg-provided libiconv + a gettext-runtime or the
// proxy-libintl shim, which this build.zig does not attempt to vendor.
const glib_core_sources = [_][]const u8{
    "garcbox.c",
    "garray.c",
    "gasyncqueue.c",
    "gatomic.c",
    "gbacktrace.c",
    "gbase64.c",
    "gbitlock.c",
    "gbookmarkfile.c",
    "gbytes.c",
    "gcharset.c",
    "gchecksum.c",
    "gconvert.c",
    "gdataset.c",
    "gdate.c",
    "gdatetime.c",
    "gdatetime-private.c",
    "gdir.c",
    "genviron.c",
    "gerror.c",
    "gfileutils.c",
    "ggettext.c",
    "ghash.c",
    "ghmac.c",
    "ghook.c",
    "ghostutils.c",
    "giochannel.c",
    "gkeyfile.c",
    "glib-init.c",
    "glib-private.c",
    "glist.c",
    "gmain.c",
    "gmappedfile.c",
    "gmarkup.c",
    "gmem.c",
    "gmessages.c",
    "gnode.c",
    "goption.c",
    "gpathbuf.c",
    "gpattern.c",
    "gpoll.c",
    "gprimes.c",
    "gqsort.c",
    "gquark.c",
    "gqueue.c",
    "grand.c",
    "grcbox.c",
    "grefcount.c",
    "grefstring.c",
    "gscanner.c",
    "gsequence.c",
    "gshell.c",
    "gslice.c",
    "gslist.c",
    "gspawn.c",
    "gstdio.c",
    "gstrfuncs.c",
    "gstring.c",
    "gstringchunk.c",
    "gstrvbuilder.c",
    "gtestutils.c",
    "gthread.c",
    "gthreadpool.c",
    "gtimer.c",
    "gtimezone.c",
    "gtrace.c",
    "gtranslit.c",
    "gtrashstack.c",
    "gtree.c",
    "guniprop.c",
    "gutf8.c",
    "gunibreak.c",
    "gunicollate.c",
    "gunidecomp.c",
    "guri.c",
    "gutils.c",
    "guuid.c",
    "gvariant.c",
    "gvariant-core.c",
    "gvariant-parser.c",
    "gvariant-serialiser.c",
    "gvarianttypeinfo.c",
    "gvarianttype.c",
    "gversion.c",
    "gwakeup.c",
    "gprint.c",
    "gprintf.c",
    // Always built regardless of platform (see library('glib-2.0', ...)).
    "deprecated/gallocator.c",
    "deprecated/gcache.c",
    "deprecated/gcompletion.c",
    "deprecated/grel.c",
    "deprecated/gthread-deprecated.c",
};

const glib_unix_sources = [_][]const u8{
    "glib-unix.c",
    "giounix.c",
    "gspawn-posix.c",
    // Linux-only (systemd journal support, no external deps).
    "gjournal-private.c",
    // subdir('libcharset').
    "libcharset/localcharset.c",
};

const glib_windows_sources = [_][]const u8{
    "gwin32.c",
    "gspawn-win32.c",
    "giowin32.c",
    // subdir('libcharset').
    "libcharset/localcharset.c",
};

// libiconv's own iconv.c/compat.c, reused as glib's real iconv() on
// Windows -- see that package's build.zig for how these were made to
// build with zig cc. Its
// localcharset.c is NOT reused: glib compiles its own copy above
// (libcharset/localcharset.c), and both define locale_charset().
const libiconv_windows_sources = [_][]const u8{ "iconv.c", "compat.c" };

// gettext-runtime/intl's sources, reused as glib's real gettext()/
// dgettext()/bindtextdomain() on Windows and musl -- see that package's
// build.zig for details. Its
// localcharset.c is likewise excluded for the same reason.
const gettext_intl_windows_sources = [_][]const u8{
    "bindtextdom.c",
    "dcgettext.c",
    "dgettext.c",
    "gettext.c",
    "finddomain.c",
    "hash-string.c",
    "loadmsgcat.c",
    "localealias.c",
    "textdomain.c",
    "l10nflist.c",
    "explodename.c",
    "dcigettext.c",
    "dcngettext.c",
    "dngettext.c",
    "ngettext.c",
    "plural.c",
    "plural-exp.c",
    "langprefs.c",
    "log.c",
    "version.c",
    "osdep.c",
    "intl-compat.c",
    "compat.c",
};

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const is_windows = target.result.os.tag == .windows;
    const needs_libintl = is_windows or target.result.abi == .musl;
    const is_glibc = target.result.os.tag == .linux and !needs_libintl;
    const libiconv_dep = if (is_windows)
        b.dependency("libiconv", .{})
    else
        null;
    const gettext_dep = if (needs_libintl)
        b.dependency("gettext", .{})
    else
        null;

    if (!is_windows and target.result.os.tag != .linux) {
        std.debug.print(
            "warning: this build.zig has only been verified against Linux (glibc) and " ++
                "Windows (mingw) targets\n",
            .{},
        );
    }

    const write_files = b.addWriteFiles();

    // Hand-written stand-in for glib/glibconfig.h (normally generated by
    // meson from glibconfig.h.in via extensive compiler probing). Values
    // below cover both a 64-bit little-endian Linux (LP64) target and a
    // 64-bit Windows/mingw (LLP64) target, selected via #ifdef _WIN32 --
    // since this header is compiled by the real target compiler, it picks
    // the right branch itself; build.zig doesn't need to generate two
    // separate variants.
    _ = write_files.add("glibconfig.h",
        \\#ifndef __GLIBCONFIG_H__
        \\#define __GLIBCONFIG_H__
        \\
        \\#include <glib/gmacros.h>
        \\#include <limits.h>
        \\#include <float.h>
        \\
        \\#define GLIB_USING_SYSTEM_PRINTF 1
        \\
        \\G_BEGIN_DECLS
        \\
        \\#define G_MINFLOAT    FLT_MIN
        \\#define G_MAXFLOAT    FLT_MAX
        \\#define G_MINDOUBLE    DBL_MIN
        \\#define G_MAXDOUBLE    DBL_MAX
        \\#define G_MINSHORT    SHRT_MIN
        \\#define G_MAXSHORT    SHRT_MAX
        \\#define G_MAXUSHORT    USHRT_MAX
        \\#define G_MININT    INT_MIN
        \\#define G_MAXINT    INT_MAX
        \\#define G_MAXUINT    UINT_MAX
        \\#define G_MINLONG    LONG_MIN
        \\#define G_MAXLONG    LONG_MAX
        \\#define G_MAXULONG    ULONG_MAX
        \\
        \\typedef signed char gint8;
        \\typedef unsigned char guint8;
        \\
        \\typedef signed short gint16;
        \\typedef unsigned short guint16;
        \\
        \\#define G_GINT16_MODIFIER "h"
        \\#define G_GINT16_FORMAT "hi"
        \\#define G_GUINT16_FORMAT "hu"
        \\
        \\typedef signed int gint32;
        \\typedef unsigned int guint32;
        \\
        \\#define G_GINT32_MODIFIER ""
        \\#define G_GINT32_FORMAT "i"
        \\#define G_GUINT32_FORMAT "u"
        \\
        \\#define G_HAVE_GINT64 1
        \\
        \\#ifdef _WIN32
        \\typedef signed long long gint64;
        \\typedef unsigned long long guint64;
        \\
        \\#define G_GINT64_CONSTANT(val)    (val##LL)
        \\#define G_GUINT64_CONSTANT(val)    (val##ULL)
        \\
        \\#define G_GINT64_MODIFIER "ll"
        \\#define G_GINT64_FORMAT "lli"
        \\#define G_GUINT64_FORMAT "llu"
        \\
        \\#define GLIB_SIZEOF_VOID_P 8
        \\#define GLIB_SIZEOF_LONG   4
        \\#define GLIB_SIZEOF_SIZE_T 8
        \\#define GLIB_SIZEOF_SSIZE_T 8
        \\
        \\typedef signed long long gssize;
        \\typedef unsigned long long gsize;
        \\#define G_GSIZE_MODIFIER "ll"
        \\#define G_GSSIZE_MODIFIER "ll"
        \\#define G_GSIZE_FORMAT "llu"
        \\#define G_GSSIZE_FORMAT "lli"
        \\
        \\#define G_MAXSIZE    G_MAXUINT64
        \\#define G_MINSSIZE    G_MININT64
        \\#define G_MAXSSIZE    G_MAXINT64
        \\#else
        \\typedef signed long gint64;
        \\typedef unsigned long guint64;
        \\
        \\#define G_GINT64_CONSTANT(val)    (val##L)
        \\#define G_GUINT64_CONSTANT(val)    (val##UL)
        \\
        \\#define G_GINT64_MODIFIER "l"
        \\#define G_GINT64_FORMAT "li"
        \\#define G_GUINT64_FORMAT "lu"
        \\
        \\#define GLIB_SIZEOF_VOID_P 8
        \\#define GLIB_SIZEOF_LONG   8
        \\#define GLIB_SIZEOF_SIZE_T 8
        \\#define GLIB_SIZEOF_SSIZE_T 8
        \\
        \\typedef signed long gssize;
        \\typedef unsigned long gsize;
        \\#define G_GSIZE_MODIFIER "l"
        \\#define G_GSSIZE_MODIFIER "l"
        \\#define G_GSIZE_FORMAT "lu"
        \\#define G_GSSIZE_FORMAT "li"
        \\
        \\#define G_MAXSIZE    G_MAXULONG
        \\#define G_MINSSIZE    G_MINLONG
        \\#define G_MAXSSIZE    G_MAXLONG
        \\#endif
        \\
        \\typedef gint64 goffset;
        \\#define G_MINOFFSET    G_MININT64
        \\#define G_MAXOFFSET    G_MAXINT64
        \\
        \\#define G_GOFFSET_MODIFIER      G_GINT64_MODIFIER
        \\#define G_GOFFSET_FORMAT        G_GINT64_FORMAT
        \\#define G_GOFFSET_CONSTANT(val) G_GINT64_CONSTANT(val)
        \\
        \\#define G_POLLFD_FORMAT "%d"
        \\
        \\#ifdef _WIN32
        \\#define GPOINTER_TO_INT(p)    ((gint)  (gint64) (p))
        \\#define GPOINTER_TO_UINT(p)    ((guint) (guint64) (p))
        \\
        \\#define GINT_TO_POINTER(i)    ((gpointer) (gint64) (i))
        \\#define GUINT_TO_POINTER(u)    ((gpointer) (guint64) (u))
        \\
        \\typedef signed long long gintptr;
        \\typedef unsigned long long guintptr;
        \\
        \\#define G_GINTPTR_MODIFIER      "ll"
        \\#define G_GINTPTR_FORMAT        "lli"
        \\#define G_GUINTPTR_FORMAT       "llu"
        \\#else
        \\#define GPOINTER_TO_INT(p)    ((gint)  (glong) (p))
        \\#define GPOINTER_TO_UINT(p)    ((guint) (gulong) (p))
        \\
        \\#define GINT_TO_POINTER(i)    ((gpointer) (glong) (i))
        \\#define GUINT_TO_POINTER(u)    ((gpointer) (gulong) (u))
        \\
        \\typedef signed long gintptr;
        \\typedef unsigned long guintptr;
        \\
        \\#define G_GINTPTR_MODIFIER      "l"
        \\#define G_GINTPTR_FORMAT        "li"
        \\#define G_GUINTPTR_FORMAT       "lu"
        \\#endif
        \\
        \\#define GLIB_MAJOR_VERSION 2
        \\#define GLIB_MINOR_VERSION 89
        \\#define GLIB_MICRO_VERSION 1
        \\
        \\#ifdef _WIN32
        \\#define G_OS_WIN32
        \\#define G_PLATFORM_WIN32
        \\#else
        \\#define G_OS_UNIX
        \\#endif
        \\
        \\#define G_VA_COPY va_copy
        \\
        \\#define G_HAVE_ISO_VARARGS 1
        \\
        \\#if __GNUC__ == 2 && __GNUC_MINOR__ == 95
        \\#  undef G_HAVE_ISO_VARARGS
        \\#endif
        \\
        \\#ifndef _MSC_VER
        \\# define G_HAVE_GNUC_VARARGS 1
        \\#endif
        \\
        \\#if defined(__SUNPRO_C) && (__SUNPRO_C >= 0x590)
        \\#define G_GNUC_INTERNAL __attribute__((visibility("hidden")))
        \\#elif defined(__SUNPRO_C) && (__SUNPRO_C >= 0x550)
        \\#define G_GNUC_INTERNAL __hidden
        \\#elif defined (__GNUC__) && defined (G_HAVE_GNUC_VISIBILITY)
        \\#define G_GNUC_INTERNAL __attribute__((visibility("hidden")))
        \\#else
        \\#define G_GNUC_INTERNAL
        \\#endif
        \\
        \\#define G_THREADS_ENABLED
        \\#ifdef _WIN32
        \\#define G_THREADS_IMPL_WIN32
        \\#else
        \\#define G_THREADS_IMPL_POSIX
        \\#endif
        \\
        \\#define G_ATOMIC_LOCK_FREE 1
        \\
        \\#define GINT16_TO_LE(val)    ((gint16) (val))
        \\#define GUINT16_TO_LE(val)    ((guint16) (val))
        \\#define GINT16_TO_BE(val)    ((gint16) GUINT16_SWAP_LE_BE (val))
        \\#define GUINT16_TO_BE(val)    (GUINT16_SWAP_LE_BE (val))
        \\
        \\#define GINT32_TO_LE(val)    ((gint32) (val))
        \\#define GUINT32_TO_LE(val)    ((guint32) (val))
        \\#define GINT32_TO_BE(val)    ((gint32) GUINT32_SWAP_LE_BE (val))
        \\#define GUINT32_TO_BE(val)    (GUINT32_SWAP_LE_BE (val))
        \\
        \\#define GINT64_TO_LE(val)    ((gint64) (val))
        \\#define GUINT64_TO_LE(val)    ((guint64) (val))
        \\#define GINT64_TO_BE(val)    ((gint64) GUINT64_SWAP_LE_BE (val))
        \\#define GUINT64_TO_BE(val)    (GUINT64_SWAP_LE_BE (val))
        \\
        \\#define GLONG_TO_LE(val)    ((glong) GINT64_TO_LE (val))
        \\#define GULONG_TO_LE(val)    ((gulong) GUINT64_TO_LE (val))
        \\#define GLONG_TO_BE(val)    ((glong) GINT64_TO_BE (val))
        \\#define GULONG_TO_BE(val)    ((gulong) GUINT64_TO_BE (val))
        \\#define GINT_TO_LE(val)        ((gint) GINT32_TO_LE (val))
        \\#define GUINT_TO_LE(val)    ((guint) GUINT32_TO_LE (val))
        \\#define GINT_TO_BE(val)        ((gint) GINT32_TO_BE (val))
        \\#define GUINT_TO_BE(val)    ((guint) GUINT32_TO_BE (val))
        \\#define GSIZE_TO_LE(val)    ((gsize) GUINT64_TO_LE (val))
        \\#define GSSIZE_TO_LE(val)    ((gssize) GINT64_TO_LE (val))
        \\#define GSIZE_TO_BE(val)    ((gsize) GUINT64_TO_BE (val))
        \\#define GSSIZE_TO_BE(val)    ((gssize) GINT64_TO_BE (val))
        \\#define G_BYTE_ORDER G_LITTLE_ENDIAN
        \\
        \\#define GLIB_SYSDEF_POLLIN =1
        \\#define GLIB_SYSDEF_POLLOUT =4
        \\#define GLIB_SYSDEF_POLLPRI =2
        \\#define GLIB_SYSDEF_POLLHUP =16
        \\#define GLIB_SYSDEF_POLLERR =8
        \\#define GLIB_SYSDEF_POLLNVAL =32
        \\
        \\#ifdef _WIN32
        \\#define G_MODULE_SUFFIX "dll"
        \\
        \\typedef void *GPid;
        \\#define G_PID_FORMAT "p"
        \\
        \\#define GLIB_SYSDEF_AF_UNIX 1
        \\#define GLIB_SYSDEF_AF_INET 2
        \\#define GLIB_SYSDEF_AF_INET6 23
        \\
        \\#define GLIB_SYSDEF_MSG_OOB 1
        \\#define GLIB_SYSDEF_MSG_PEEK 2
        \\#define GLIB_SYSDEF_MSG_DONTROUTE 4
        \\
        \\#define G_DIR_SEPARATOR '\\'
        \\#define G_DIR_SEPARATOR_S "\\"
        \\#define G_SEARCHPATH_SEPARATOR ';'
        \\#define G_SEARCHPATH_SEPARATOR_S ";"
        \\#else
        \\#define G_MODULE_SUFFIX "so"
        \\
        \\typedef int GPid;
        \\#define G_PID_FORMAT "i"
        \\
        \\#define GLIB_SYSDEF_AF_UNIX 1
        \\#define GLIB_SYSDEF_AF_INET 2
        \\#define GLIB_SYSDEF_AF_INET6 10
        \\
        \\#define GLIB_SYSDEF_MSG_OOB 1
        \\#define GLIB_SYSDEF_MSG_PEEK 2
        \\#define GLIB_SYSDEF_MSG_DONTROUTE 4
        \\
        \\#define G_DIR_SEPARATOR '/'
        \\#define G_DIR_SEPARATOR_S "/"
        \\#define G_SEARCHPATH_SEPARATOR ':'
        \\#define G_SEARCHPATH_SEPARATOR_S ":"
        \\#endif
        \\
        \\G_END_DECLS
        \\
        \\#endif /* __GLIBCONFIG_H__ */
        \\
    );

    // Hand-written stand-in for glib's config.h (normally generated by
    // meson from ~150 compiler probes across the whole glib/gobject/gio
    // tree). Only a conservative subset relevant to the core glib_sources
    // above is set; every HAVE_* symbol not listed here is guarded by an
    // #ifdef with a working (if sometimes slower or less featureful)
    // fallback in the source, so leaving them undefined is safe.
    _ = write_files.add("config.h",
        \\#ifndef __CONFIG_H__
        \\#define __CONFIG_H__
        \\
        \\#define PACKAGE_NAME "glib"
        \\#define PACKAGE_VERSION "2.89.1"
        \\#define GETTEXT_PACKAGE "glib20"
        \\#define GLIB_LOCALE_DIR "/usr/share/locale"
        \\
        \\#define GLIB_INTERFACE_AGE 0
        \\#define GLIB_BINARY_AGE 8901
        \\
        \\// A real gettext is available on every target this build.zig
        \\// supports: glibc ships one as part of libc itself, while musl
        \\// and Windows link the Zig gettext package's libintl sources.
        \\#define ENABLE_NLS 1
        \\#define HAVE_BIND_TEXTDOMAIN_CODESET 1
        \\
        \\// Modern glibc's vsnprintf/snprintf/printf are already C99/POSIX
        \\// compliant, so use them directly instead of bundling gnulib's
        \\// vasnprintf-based reimplementation (glib/gnulib/, not compiled
        \\// by this build.zig at all).
        \\#define USE_SYSTEM_PRINTF 1
        \\
        \\#define SIZEOF_CHAR 1
        \\#define SIZEOF_SHORT 2
        \\#define SIZEOF_INT 4
        \\#ifdef _WIN32
        \\#define SIZEOF_LONG 4
        \\#else
        \\#define SIZEOF_LONG 8
        \\#endif
        \\#define SIZEOF_LONG_LONG 8
        \\#define SIZEOF_VOID_P 8
        \\#define SIZEOF_SIZE_T 8
        \\#define SIZEOF_SSIZE_T 8
        \\#define SIZEOF_PTRDIFF_T 8
        \\#ifdef _WIN32
        \\#define SIZEOF_WCHAR_T 2
        \\#else
        \\#define SIZEOF_WCHAR_T 4
        \\#endif
        \\#define SIZEOF_TIME_T 8
        \\
        \\#ifdef _WIN32
        \\#define THREADS_WIN32 1
        \\#else
        \\#define THREADS_POSIX 1
        \\#endif
        \\
        \\#define HAVE_STDINT_H 1
        \\#define HAVE_INTTYPES_H 1
        \\#define HAVE_UNISTD_H 1
        \\#define HAVE_SYS_TYPES_H 1
        \\#define HAVE_STDATOMIC_H 1
        \\// The following are all POSIX-only (mingw has none of them);
        \\// every use is guarded with a working fallback in the source.
        \\#ifndef _WIN32
        \\#define HAVE_SYS_TIME_H 1
        \\#define HAVE_SYS_SELECT_H 1
        \\#define HAVE_SYS_RESOURCE_H 1
        \\#define HAVE_SYS_PRCTL_H 1
        \\#define HAVE_SYS_PARAM_H 1
        \\#define HAVE_SYS_AUXV_H 1
        \\#endif
        \\#define HAVE_DIRENT_H 1
        \\#ifndef _WIN32
        \\#define HAVE_POLL_H 1
        \\#define HAVE_SCHED_H 1
        \\#define HAVE_FTW_H 1
        \\#endif
        \\
        \\#define HAVE_ICONV 1
        \\#ifndef _WIN32
        \\#define HAVE_LANGINFO_CODESET 1
        \\#define HAVE_CODESET 1
        \\#endif
        \\#define HAVE_SETLOCALE 1
        \\
        \\#ifndef _WIN32
        \\#define HAVE_POLL 1
        \\#define HAVE_PPOLL 1
        \\#define HAVE_MMAP 1
        \\#define HAVE_GETAUXVAL 1
        \\#define HAVE_GETRESUID 1
        \\#define HAVE_GETPWUID_R 1
        \\#define HAVE_GETPWNAM_R 1
        \\#endif
        \\
        \\#ifndef _WIN32
        \\#define HAVE_LOCALTIME_R 1
        \\#define HAVE_GMTIME_R 1
        \\#define HAVE_TIMEGM 1
        \\#endif
        \\
        \\#ifndef _WIN32
        \\#define HAVE_VASPRINTF 1
        \\#define HAVE_STPCPY 1
        \\#endif
        \\#define HAVE_STRCASECMP 1
        \\#define HAVE_STRNCASECMP 1
        \\#ifndef _WIN32
        \\#define HAVE_STRSIGNAL 1
        \\#define HAVE_STRERROR_R 1
        \\#define HAVE_MEMMEM 1
        \\#endif
        \\
        \\#ifndef _WIN32
        \\#define HAVE_POSIX_MEMALIGN 1
        \\#define HAVE_FSYNC 1
        \\#define HAVE_EVENTFD 1
        \\#define HAVE_O_CLOEXEC 1
        \\#define HAVE_SOCK_CLOEXEC 1
        \\#define HAVE_POSIX_SPAWN 1
        \\#define HAVE_SPAWN_H 1
        \\#else
        \\#define HAVE__ALIGNED_MALLOC 1
        \\#endif
        \\
        \\#ifndef _WIN32
        \\#define HAVE_PTHREAD_ATTR_SETSTACKSIZE 1
        \\#define HAVE_PTHREAD_CONDATTR_SETCLOCK 1
        \\#define HAVE_PTHREAD_SETNAME_NP_WITH_TID 1
        \\#define HAVE_PTHREAD_GETNAME_NP 1
        \\#define HAVE_CLOCK_NANOSLEEP 1
        \\#define HAVE_PTHREAD_GETAFFINITY_NP 1
        \\
        \\#define HAVE_STRUCT_TM_TM_GMTOFF 1
        \\#endif
        \\
        \\#define G_HAVE_GNUC_VISIBILITY 1
        \\
        \\#endif /* __CONFIG_H__ */
        \\
    );

    const generated_headers = write_files.getDirectory();

    // Generated via glib's own tools/gen-visibility-macros.py (same
    // generator meson uses), so these two headers are exact, not
    // hand-approximated like config.h/glibconfig.h above. Requires
    // a Python 3 interpreter on PATH at build time, as either
    // `python` (typical on Windows) or `python3` (typical on Linux/macOS).
    // `python` is tried first: on Windows, resolving a missing real
    // interpreter can land on the "App Execution Alias" stub
    // (WindowsApps\python3.exe), a reparse point that crashes zig's
    // std.Build.findProgram (unhandled NTSTATUS) rather than reporting
    // not-found -- so we only fall back to "python3" where a real
    // "python" isn't found at all (typical on Linux CI runners).
    const python_exe = b.findProgram(&.{"python"}, &.{}) catch
        b.findProgram(&.{"python3"}, &.{}) catch
        @panic("python or python3 not found on PATH");
    const gen_script = b.path("tools/gen-visibility-macros.py");

    const gen_versions = b.addSystemCommand(&.{ python_exe, "-B" });
    gen_versions.addFileArg(gen_script);
    gen_versions.addArgs(&.{ "2.89.1", "versions-macros" });
    gen_versions.addFileArg(b.path("glib/gversionmacros.h.in"));
    const gversionmacros_h = gen_versions.addOutputFileArg("gversionmacros.h");

    const gen_visibility = b.addSystemCommand(&.{ python_exe, "-B" });
    gen_visibility.addFileArg(gen_script);
    gen_visibility.addArgs(&.{ "2.89.1", "visibility-macros", "GLIB" });
    const glib_visibility_h = gen_visibility.addOutputFileArg("glib-visibility.h");

    // gmodule.h (installed further below, verbatim from gmodule/gmodule.h)
    // needs gmodule/gmodule-visibility.h, generated the same way as
    // glib-visibility.h above (see glib/gmodule/meson.build). We only
    // install the *header*, not a working gmodule implementation: nothing
    // in this build actually calls a g_module_* function (gmodule.c is
    // intentionally not built, matching the "no gobject/gio/gmodule"
    // scope of this build.zig), but some consumers (e.g. QEMU's
    // include/qemu/transactions.h) unconditionally #include <gmodule.h>
    // regardless of whether they use it, since a normal/full glib install
    // always has it. Making the header parseable is enough for that.
    const gen_gmodule_visibility = b.addSystemCommand(&.{ python_exe, "-B" });
    gen_gmodule_visibility.addFileArg(gen_script);
    gen_gmodule_visibility.addArgs(&.{ "2.89.1", "visibility-macros", "GMODULE" });
    const gmodule_visibility_h = gen_gmodule_visibility.addOutputFileArg("gmodule-visibility.h");

    const mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    mod.addIncludePath(generated_headers);
    mod.addIncludePath(b.path("glib"));
    // Consumers include e.g. <glib/gtypes.h>, so the parent of glib/ needs
    // to be on the include path too (matches meson's glibinc).
    mod.addIncludePath(b.path("."));
    mod.addCMacro("HAVE_CONFIG_H", "1");
    mod.addCMacro("GLIB_COMPILATION", "1");
    mod.addCMacro("G_LOG_DOMAIN", "\"GLib\"");
    mod.addCMacro("GLIB_CHARSETALIAS_DIR", "\"\"");
    if (is_glibc)
        mod.addCMacro("STRERROR_R_CHAR_P", "1");
    // Needed for GNU/POSIX extensions used by the sources below, including
    // ppoll() in gmain.c. The generated config distinguishes glibc's
    // char*-returning strerror_r() from musl's POSIX int-returning form.
    mod.addCMacro("_GNU_SOURCE", "1");

    // gversionmacros.h/glib-visibility.h are #included (as
    // "gversionmacros.h") from glib/gmacros.h et al, so they need to live
    // next to the other glib/*.h headers on the include path; addCopyFile
    // them into the same generated-headers directory used above.
    // Placed under a "glib/" subdirectory since e.g. gtypes.h includes
    // them as <glib/gversionmacros.h> / <glib/glib-visibility.h>.
    const glib_headers_dir = b.addNamedWriteFiles("glib-generated-headers");
    _ = glib_headers_dir.addCopyFile(gversionmacros_h, "glib/gversionmacros.h");
    _ = glib_headers_dir.addCopyFile(glib_visibility_h, "glib/glib-visibility.h");
    mod.addIncludePath(glib_headers_dir.getDirectory());

    mod.addCSourceFiles(.{
        .root = b.path("glib"),
        .files = &glib_core_sources,
        .flags = &.{"-std=gnu99"},
    });
    mod.addCSourceFiles(.{
        .root = b.path("glib"),
        .files = if (is_windows) &glib_windows_sources else &glib_unix_sources,
        .flags = &.{"-std=gnu99"},
    });

    if (is_windows) {
        // Provide the real iconv() Windows lacks natively, which
        // gconvert.c calls unconditionally. This is built as a separate
        // library artifact rather than merged into this module because
        // some of its sources #include <config.h> with
        // angle brackets (searches the shared -I list in order, unlike
        // quote-includes which check the including file's own directory
        // first), which would otherwise collide with glib's own
        // <config.h> whichever ends up earlier on this module's -I list.
        mod.addIncludePath(libiconv_dep.?.path("include"));
    }

    if (needs_libintl) {
        // libgnuintl.h (gettext's generated public header) needs to be
        // found as "libintl.h", which is what ggettext.c #includes.
        const libintl_headers = b.addNamedWriteFiles("libintl-header");
        _ = libintl_headers.addCopyFile(
            gettext_dep.?.path("gettext-runtime/intl/libgnuintl.h"),
            "libintl.h",
        );
        mod.addIncludePath(libintl_headers.getDirectory());
    }

    if (is_windows) {
        mod.linkSystemLibrary("ws2_32", .{});
        mod.linkSystemLibrary("winmm", .{});
        // gutils.c's Windows special-folder lookups need CoTaskMemFree
        // (ole32) and SHGetKnownFolderPath (shell32).
        mod.linkSystemLibrary("ole32", .{});
        mod.linkSystemLibrary("shell32", .{});
    }

    const lib = b.addLibrary(.{
        .name = "glib-2.0",
        .linkage = .static,
        .root_module = mod,
    });
    b.installArtifact(lib);

    if (is_windows) {
        const iconv_mod = b.createModule(.{ .target = target, .optimize = optimize, .link_libc = true });
        iconv_mod.addIncludePath(libiconv_dep.?.path("include"));
        iconv_mod.addIncludePath(libiconv_dep.?.path("libcharset/include"));
        iconv_mod.addCMacro("HAVE_CONFIG_H", "1");
        iconv_mod.addCSourceFiles(.{
            .root = libiconv_dep.?.path("lib"),
            .files = &libiconv_windows_sources,
            .flags = &.{ "-std=gnu99", "-w" },
        });
        const iconv_lib = b.addLibrary(.{ .name = "iconv", .linkage = .static, .root_module = iconv_mod });
        b.installArtifact(iconv_lib);
        mod.linkLibrary(iconv_lib);

        lib.installHeader(libiconv_dep.?.path("include/iconv.h"), "iconv.h");
    }

    if (needs_libintl) {
        const intl_mod = b.createModule(.{ .target = target, .optimize = optimize, .link_libc = true });
        intl_mod.addIncludePath(gettext_dep.?.path("gettext-runtime/intl"));
        intl_mod.addCMacro("HAVE_CONFIG_H", "1");
        intl_mod.addCSourceFiles(.{
            .root = gettext_dep.?.path("gettext-runtime/intl"),
            .files = &gettext_intl_windows_sources,
            .flags = &.{ "-std=gnu99", "-w" },
        });
        // libgnuintl.in.h redirects plain setlocale() to libintl_setlocale()
        // on Windows unconditionally, and glib's own gdatetime.c calls
        // setlocale() -- see cataggar/gettext's setlocale-compat.c for the
        // full rationale (a deliberately minimal shim, not gettext's real
        // setlocale.c, to avoid a large extra gnulib dependency chain).
        if (is_windows) {
            intl_mod.addCSourceFile(.{
                .file = gettext_dep.?.path("setlocale-compat.c"),
                .flags = &.{ "-std=gnu99", "-w" },
            });
        }
        const intl_lib = b.addLibrary(.{ .name = "intl", .linkage = .static, .root_module = intl_mod });
        b.installArtifact(intl_lib);
        mod.linkLibrary(intl_lib);

        lib.installHeader(gettext_dep.?.path("gettext-runtime/intl/libgnuintl.h"), "libintl.h");
    }

    // Install headers so zig-out/include is directly usable by a
    // consumer: <glib.h> plus every glib/*.h (galloca.h, garray.h, ...)
    // under zig-out/include/glib/, and the hand-written/generated headers
    // that normally live in meson's separate config/glibinc dirs.
    lib.installHeader(b.path("glib/glib.h"), "glib.h");
    lib.installHeadersDirectory(b.path("glib"), "glib", .{});
    lib.installHeader(generated_headers.join(b.allocator, "glibconfig.h") catch @panic("OOM"), "glibconfig.h");
    lib.installHeader(gversionmacros_h, "glib/gversionmacros.h");
    lib.installHeader(glib_visibility_h, "glib/glib-visibility.h");

    // See the gen_gmodule_visibility comment above: header-only, no
    // gmodule.c/gmodule-deprecated.c compiled in.
    lib.installHeader(b.path("gmodule/gmodule.h"), "gmodule.h");
    lib.installHeader(gmodule_visibility_h, "gmodule/gmodule-visibility.h");
}
